apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
      - name: node-hello
        image: sanjana0910/practice1:v1 
        ports:
        - containerPort: 3000
